### ISSUE TITLE
How to download the deeplabv3 model in your code?

### ISSUE THREAD

**Issue by zhongwenkun886** [feng1sun/algo#1]
Hi ,feng1sun,
Could you please tell me how to download the deeplabv3 model (frozen_inference_graph.xml) in your  algo/openvino/deeplabv3/main.cpp ? 
Thanks!

**Comment by feng1sun** [comment]
frozen_inference_graph.xml is transformed by openvino. you can using Model Optimizer in <openvino_install>/computer_vision_sdk/deployment_tools/model_optimizer

**Comment by feng1sun** [comment]
> Hi ,feng1sun,
> Could you please tell me how to download the deeplabv3 model (frozen_inference_graph.xml) in your algo/openvino/deeplabv3/main.cpp ?
> Thanks!

frozen_inference_graph.xml is transformed by openvino. you can using Model Optimizer in <openvino_install>/computer_vision_sdk/deployment_tools/model_optimizer
